name: Build vscode server tmp
run-name: Build vscode server ${{ github.event.inputs.branch }} tmp
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tasks:
          # [
          #   9fc2a7aeb69,
          #   a55ca03d697,
          #   8fbd5025bfd,
          #   1d92f24bd8c,
          #   12f6838c4fd,
          #   9a207df8414,
          #   c9a90f9b4ef,
          #   9f73e42b97c, bad
          #   0fd18a31260,good
          #   c204ef06857,
          #   33f712ff824, good
          #   65943425f0f,
          #   db2c8785d49,
          #   4e6d11e9f11,
          # ]
          # [
          #   50e60d26d76,
          #   2879523ba19,
          #   0c8e9bf15de,
          #   73f87ec974e,
          #   358b12e31e4,
          #   a49098ef6a9,
          #   5d992684162, bad
          #   1f3c4bdc9e1,good
          #   dd076d09984,
          #   1a4bd0bd98d,good
          #   6254eb1f4d0,
          #   b052d34e5cc
          # ]
          [
            7425fbc5f30,
            e984f918dc1,
            e8ce9b3b29f,
            df2dd86b0c1,
            64783a4eb9e,
            8de9ba22b2c,
            cb6c07d46d8,
            9891465832b,
            74825844e1c,
            73f8cc3cb3d,
            54cbd06803b,
            c668e31a4f2,
            c028993bd1b,
            a424b054e91,
            6254eb1f4d0,
            319b62aa16d,
            c51428211f8,
            c90a53543b6,
            fba876b51f7,
          ]

    steps:
      - uses: actions/checkout@main
      - name: Checkout repository
        run: |
          env
          cat /proc/cpuinfo
          tree -L 2 ${GITHUB_WORKSPACE}

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.0
        with:
          # Version Spec of the version to use. Examples: 12.x, 10.15.1, >=10.15.0.
          node-version: 18.15.0

      - name: Fetch source code and patch
        run: |
          git clone https://github.com/microsoft/vscode --branch=release/1.85
          cd vscode

          git checkout ${{matrix.tasks}}

      - name: Build
        run: |
          sudo apt install g++ libx11-dev libxkbfile-dev libsecret-1-dev libkrb5-dev
          cd vscode
          ## Electron and browsers are not required
          ## for code-server build.
          export ELECTRON_SKIP_BINARY_DOWNLOAD=1
          export PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1

          yarn
          yarn gulp vscode-web

      - name: Test output
        run: |
          tree -L 1

      - name: Package
        run: |
          tar -c vscode-web | xz -T0 > "${GITHUB_WORKSPACE}/${{matrix.tasks}}.tar.xz"

      - name: Upload
        uses: actions/upload-artifact@main
        with:
          name: ${{ matrix.tasks }}.tar.xz
          path: ${{matrix.tasks}}.tar.xz
