name: Build musl cross

on:
  push:
    paths:
      - ".github/workflows/build_musl_cross.yaml"
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        host:
          - x86_64-linux-musl
          - aarch64-linux-musl
        target:
          - x86_64-linux-musl
          - aarch64-linux-musl

    steps:
      - name: Clone musl-cross-make
        run: git clone https://github.com/DanielMYT/musl-cross-make

      - name: Patch source
        working-directory: musl-cross-make
        run: |
          ## Tar no verbose
          cat Makefile | sed 's/tar zxvf/tar zxf/' | sed 's/tar jxvf/tar jxf/' | sed 's/tar Jxvf/tar Jxf/' > Makefile_tmp
          mv Makefile_tmp Makefile

      - name: "Build bootstrap toolchain host: ${{matrix.host}}"
        env:
          OUTPUT: ${{matrix.host}}
        working-directory: musl-cross-make
        run: |
          cat<<EOF>config.mak
          TARGET = ${{matrix.host}}

          BINUTILS_VER = 2.41
          GCC_VER = 13.2.0
          MUSL_VER = 1.2.4
          GMP_VER = 6.3.0
          MPC_VER = 1.3.1
          MPFR_VER = 4.2.1
          ISL_VER = 0.26
          LINUX_VER = 6.6.2

          DL_CMD = curl -C - -Ls -o

          COMMON_CONFIG += CFLAGS="-g0 -Os" CXXFLAGS="-g0 -Os" LDFLAGS="-s"
          BINUTILS_CONFIG += --disable-gprofng
          EOF

          make -j$(nproc --all) || make -j$(nproc --all) || make -j$(nproc --all)
          make install

          mv output ${{matrix.host}}-bootstrap

      - name: "Bootstrap build toolchain host: ${{matrix.host}} target: ${{matrix.target}}"
        working-directory: musl-cross-make
        run: |
          sudo apt install qemu-user-static binfmt-support
          export PATH=${PWD}/${{matrix.host}}-bootstrap/bin:$PATH

          ${{matrix.target}}-gcc --version
          make clean

          cat<<EOF>config.mak
          TARGET = ${{matrix.target}}

          BINUTILS_VER = 2.41
          GCC_VER = 13.2.0
          MUSL_VER = 1.2.4
          GMP_VER = 6.3.0
          MPC_VER = 1.3.1
          MPFR_VER = 4.2.1
          ISL_VER = 0.26
          LINUX_VER = 6.6.2

          DL_CMD = curl -C - -Ls -o

          COMMON_CONFIG += CC="${{matrix.target}}-gcc -static --static" CXX="${{matrix.target}}-g++ -static --static"
          COMMON_CONFIG += CFLAGS="-g0 -Os" CXXFLAGS="-g0 -Os" LDFLAGS="-s"
          BINUTILS_CONFIG += --disable-gprofng
          EOF

          make -j$(nproc --all)
          make install
          mv output ${{matrix.target}}-${{matrix.host}}

      - name: Checkout output
        working-directory: musl-cross-make
        run: |
          file ${{matrix.target}}-${{matrix.host}}/bin/*

      - name: Compress ${{matrix.target}}-${{matrix.host}}
        working-directory: musl-cross-make
        run: |
          tar -c ${{matrix.target}}-${{matrix.host}} | xz -T0 < ${{matrix.target}}-${{matrix.host}}.tar.xz

      - name: Upload ${{matrix.target}}-cross artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{matrix.target}}-${{matrix.host}}.tar.xz
          path: musl-cross-make/${{matrix.target}}-${{matrix.host}}.tar.xz
