name: Build musl cross

on:
  push:
    paths:
      - ".github/workflows/build_musl_cross.yaml"
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target:
          - aarch64-linux-musl
          - x86_64-linux-musl

    steps:
      - name: Clone musl-cross-make
        run: git clone https://github.com/DanielMYT/musl-cross-make

      - name: Patch source
        working-directory: musl-cross-make
        run: |
          ## Tar no verbose
          cat Makefile | sed 's/tar zxvf/tar zxf/' | sed 's/tar jxvf/tar jxf/' | sed 's/tar Jxvf/tar Jxf/' > Makefile_tmp
          mv Makefile_tmp Makefile

      - name: Build bootstrap toolchain ${{matrix.target}}
        working-directory: musl-cross-make
        run: |
          cat<<EOF>config.mak
          TARGET = $(uname -m)-linux-musl

          BINUTILS_VER = 2.41
          GCC_VER = 13.2.0
          MUSL_VER = 1.2.4
          GMP_VER = 6.3.0
          MPC_VER = 1.3.1
          MPFR_VER = 4.2.1
          ISL_VER = 0.26
          LINUX_VER = 6.6.2

          DL_CMD = curl -C - -Ls -o

          COMMON_CONFIG += CFLAGS="-g0 -Os" CXXFLAGS="-g0 -Os" LDFLAGS="-s"
          BINUTILS_CONFIG += --disable-gprofng
          EOF

          make -j$(nproc --all) || make -j$(nproc --all) || make -j$(nproc --all)
          make install

          mv output ${{matrix.target}}-bootstrap

      - name: Bootstrap build toolchain ${{matrix.target}}
        working-directory: musl-cross-make
        run: |
          make clean
          export PATH=${PWD}/${{matrix.target}}-bootstrap/bin:$PATH

          cat<<EOF>config.mak
          TARGET = ${{matrix.target}}

          BINUTILS_VER = 2.41
          GCC_VER = 13.2.0
          MUSL_VER = 1.2.4
          GMP_VER = 6.3.0
          MPC_VER = 1.3.1
          MPFR_VER = 4.2.1
          ISL_VER = 0.26
          LINUX_VER = 6.6.2

          DL_CMD = curl -C - -Ls -o

          COMMON_CONFIG += CC="${{matrix.target}}-gcc -static --static" CXX="${{matrix.target}}-g++ -static --static"
          COMMON_CONFIG += CFLAGS="-g0 -Os" CXXFLAGS="-g0 -Os" LDFLAGS="-s"
          BINUTILS_CONFIG += --disable-gprofng
          EOF

          make -j$(nproc --all)
          make install
          mv output ${{matrix.target}}-toolchain

      - name: Checkout output
        run: |
          file ${{matrix.target}}-*/bin/*

      # - name: Compress ${{matrix.target}}-cross
      #   run: |
      #        cd musl-cross
      #        tar -cvzf ${{matrix.target}}-cross.tar.gz ${{matrix.target}}-cross
      #        ls -al

      # - name: Upload ${{matrix.target}}-cross artifacts
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: ${{matrix.target}}-cross.tar.xz
      #     path: ${{matrix.target}}-cross.tar.xz
