name: Build vscode server tmp
run-name: Build vscode server ${{ github.event.inputs.branch }} tmp
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tasks:
          [
            9fc2a7aeb69,
            a55ca03d697,
            8fbd5025bfd,
            1d92f24bd8c,
            12f6838c4fd,
            9a207df8414,
            c9a90f9b4ef,
            9f73e42b97c,
            0fd18a31260,
            c204ef06857,
            33f712ff824,
            65943425f0f,
            db2c8785d49,
            4e6d11e9f11,
          ]

    steps:
      - uses: actions/checkout@main
      - name: Checkout repository
        run: |
          env
          cat /proc/cpuinfo
          tree -L 2 ${GITHUB_WORKSPACE}

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.0
        with:
          # Version Spec of the version to use. Examples: 12.x, 10.15.1, >=10.15.0.
          node-version: 18.15.0

      - name: Fetch source code and patch
        run: |
          git clone https://github.com/microsoft/vscode --branch=release/1.85
          cd vscode

          git checkout ${{matrix.tasks}}

      - name: Build
        run: |
          sudo apt install g++ libx11-dev libxkbfile-dev libsecret-1-dev libkrb5-dev
          cd vscode
          ## Electron and browsers are not required
          ## for code-server build.
          export ELECTRON_SKIP_BINARY_DOWNLOAD=1
          export PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1

          yarn
          yarn gulp vscode-web

      - name: Test output
        run: |
          tree -L 1

      - name: Package
        run: |
          tar -c "${dir}" | xz -T0 > "${GITHUB_WORKSPACE}/${{matrix.tasks}}.tar.xz"

      - name: Upload
        uses: actions/upload-artifact@main
        with:
          name: ${{ matrix.tasks }}.tar.xz
          path: ${{matrix.tasks}}.tar.xz
