name: Build musl toolchain
run-name: Build musl toolchain (${{ github.event.head_commit.message }})

on:
  push:
    paths:
      - ".github/workflows/build_musl_cross.yaml"
  workflow_dispatch:

jobs:
  Build:
    permissions:
      contents: write
      actions: write
    name: Build ${{matrix.target}}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target:
          - x86_64-linux-musl
          - aarch64-linux-musl
    env:
      TARGET: ${{matrix.target}}

    steps:
      - name: Clone musl-cross-make
        run: git clone https://github.com/DanielMYT/musl-cross-make

      - name: Cache sources
        id: cache-sources
        uses: actions/cache@v3
        with:
          path: |
            musl-cross-make/sources/
          key: build_musl_cross-${{hashFiles('musl-cross-make/sources/*.tar.*')}}
          restore-keys: |
            build_musl_cross-${{hashFiles('musl-cross-make/sources/*.tar.*')}}
            build_musl_cross-

      - name: Patch source
        working-directory: musl-cross-make
        run: |
          ## Tar no verbose
          cat Makefile | sed 's/tar zxvf/tar zxf/' | sed 's/tar jxvf/tar jxf/' | sed 's/tar Jxvf/tar Jxf/' > Makefile_tmp
          mv Makefile_tmp Makefile
      - name: Write config.mak
        working-directory: musl-cross-make
        run: |
          cat<<EOF>config.mak
          BINUTILS_VER = 2.41
          GCC_VER = 13.2.0
          MUSL_VER = 1.2.4
          GMP_VER = 6.3.0
          MPC_VER = 1.3.1
          MPFR_VER = 4.2.1
          ISL_VER = 0.26
          LINUX_VER = 6.6.2
          DL_CMD = curl -C - -Ls -o
          STAT = -static --static
          COMMON_CONFIG += CFLAGS="-g0 -Os \${STAT}" CXXFLAGS="-g0 -Os \${STAT}" FFLAGS="\${STAT}" LDFLAGS="-w -s \${STAT}"
          BINUTILS_CONFIG += --disable-gprofng
          GCC_CONFIG += --with-sysroot=/\${TARGET}
          EOF
      - name: Cross build ${{matrix.target}}
        working-directory: musl-cross-make
        run: |
          ## build via command, no make then install, no relative output path
          make install \
            TARGET=${TARGET} OUTPUT=${PWD}/${TARGET}-cross \
            -j$(nproc)

          rm -rf build/local/${TARGET}
      - name: Checkout ${{matrix.target}}-cross
        working-directory: musl-cross-make
        run: |
          tree -aL 1
          file ${TARGET}-cross/bin/*
      - name: Native build ${{matrix.target}}
        working-directory: musl-cross-make
        run: |
          sudo apt install qemu-user-static binfmt-support
          export PATH=${PWD}/${TARGET}-cross/bin:$PATH
          make install NATIVE=1 \
            TARGET=${TARGET} CROSS_COMPILE=${TARGET}- OUTPUT=${PWD}/${TARGET}-native \
            -j$(($(nproc) - 1))
      - name: Checkout ${{matrix.target}}-native
        working-directory: musl-cross-make
        run: |
          tree -aL 1
          file ${TARGET}-native/bin/*
      - name: Compress
        working-directory: musl-cross-make
        run: |
          tar -c ${TARGET}-cross | xz -T0 > ${TARGET}-cross.tar.xz
          tar -c ${TARGET}-native | xz -T0 > ${TARGET}-native.tar.xz
      - name: Upload ${{matrix.target}}-cross
        uses: actions/upload-artifact@main
        with:
          name: ${{matrix.target}}-cross.tar.xz
          path: musl-cross-make/${{matrix.target}}-cross.tar.xz
      - name: Upload ${{matrix.target}}-native
        uses: actions/upload-artifact@main
        with:
          name: ${{matrix.target}}-native.tar.xz
          path: musl-cross-make/${{matrix.target}}-native.tar.xz
      - name: Get Date
        run: echo DATE=$(date +"%Y-%m-%d %H:%M:%S") >> ${GITHUB_ENV}
      - name: Upload release
        uses: ncipollo/release-action@v1.13.0
        with:
          tag: "v1.0.0"
          artifacts: |
            musl-cross-make/${{matrix.target}}-cross.tar.xz
            musl-cross-make/${{matrix.target}}-native.tar.xz
          allowUpdates: true
          replacesArtifacts: true
          body: |
            [action](${{github.server_url}}/${{github.repository}}/actions/runs/${{github.run_id}})
            * BINUTILS_VER = 2.41
            * GCC_VER = 13.2.0
            * MUSL_VER = 1.2.4
            * GMP_VER = 6.3.0
            * MPC_VER = 1.3.1
            * MPFR_VER = 4.2.1
            * ISL_VER = 0.26
            * LINUX_VER = 6.6.2
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2.0.6
        with:
          delete_workflow_pattern: "build_musl_cross.yaml"
          retain_days: 0
          keep_minimum_runs: 1