name: Build musl cross

on:
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    # strategy:
    #    fail-fast: false
    #    matrix:
    #      target: [aarch64-linux-musl,x86_64-linux-musl]
    #      #target: [armv7l-linux-musleabihf]
    env:
      TARGET: aarch64-linux-musl
    steps:
      - name: Clone musl-cross-make
        run: git clone https://github.com/DanielMYT/musl-cross-make

      - name: Build
        working-directory: musl-cross-make
        run: |
          cat<<EOF>config.mak
          DL_CMD = curl -C - -Ls -o

          TARGET = ${TARGET}

          BINUTILS_VER = 2.41
          GCC_VER = 13.2.0
          MUSL_VER = 1.2.4
          GMP_VER = 6.3.0
          MPC_VER = 1.3.1
          MPFR_VER = 4.2.1
          ISL_VER = 0.26
          LINUX_VER = 6.6.2

          # Recommended options for smaller build for deploying binaries:
          COMMON_CONFIG += CFLAGS="-g0 -Os" CXXFLAGS="-g0 -Os" LDFLAGS="-w -s"
          EOF

          ## Tar no verbose
          cat Makefile | sed 's/tar zxvf/tar zxf/' | sed 's/tar jxvf/tar jxf/' | sed 's/tar Jxvf/tar Jxf/' > Makefile_tmp
          mv Makefile_tmp Makefile

          make -j$(nproc)
          make install

          ls -al
          file output/bin/*

          mv output ${TARGET}-cross
          tar -c ${TARGET}-cross | xz -T0 > ${TARGET}-cross.tar.xz

      # - name: Compress ${TARGET}-cross
      #   run: |
      #        cd musl-cross
      #        tar -cvzf ${TARGET}-cross.tar.gz ${TARGET}-cross
      #        ls -al

      - name: Upload ${TARGET}-cross artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${TARGET}-cross.tar.xz
          path: ${TARGET}-cross.tar.xz
