name: Build llvm
run-name: Build llvm ${{github.event.inputs.tag}}
on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Release tag:"
        default: "llvmorg-17.0.6"
        required: true

jobs:
  build-llvm:
    runs-on: ubuntu-latest
    # env:
    #   arch: ${{github.event.inputs.msg}}
    # strategy:
    #   fail-fast: false
    #   matrix:
    #     target_arch: [matrix0, matrix1]

    steps:
      - name: Checkout llvm-project
        uses: actions/checkout@v4.1.1
        with:
          repository: llvm/llvm-project
          ref: ${{github.event.inputs.tag}}

      - name: Build
        run: |
          mkdir build
          cd build
          # -DLLVM_ENABLE_PROJECTS="clang;clang-tools-extra;compiler-rt;lld;lldb;mlir;openmp;polly" \

          sudo apt install ninja-build

          cmake \
            ../llvm \
            -DCMAKE_BUILD_TYPE=Release \
            -DLLVM_TARGETS_TO_BUILD="AArch64" \
            -DLLVM_HOST_TRIPLE=aarch64-linux-musl \
            -G "Ninja"

          cmake --build .

          tree bin
          file bin/*

      # - name: Upload
      #   uses: actions/upload-artifact@main
      #   with:
      #     name: ${{matrix.target_arch}}
      #     path: echo_hello.tar.xz
