name: Build llvm
run-name: Build llvm ${{github.event.inputs.tag}}
on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Release tag:"
        default: "llvmorg-17.0.6"
        required: true

jobs:
  build-llvm:
    runs-on: ubuntu-latest
    # env:
    #   arch: ${{github.event.inputs.msg}}
    # strategy:
    #   fail-fast: false
    #   matrix:
    #     target_arch: [matrix0, matrix1]

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          repository: llvm/llvm-project
          ref: ${{github.event.inputs.tag}}

      - name: Print env
        run: |
          mkdir build
          cd build
          # -DLLVM_ENABLE_PROJECTS="clang;clang-tools-extra;compiler-rt;lld;lldb;mlir;openmp;polly" \

          sudo apt install ninja-build

          cmake \
            ../llvm \
            -DCMAKE_BUILD_TYPE=Release \
            -DLLVM_TARGETS_TO_BUILD="AArch64" \
            -DLLVM_HOST_TRIPLE=aarch64-linux-musl \
            -G "Ninja"
          
          cmake --build .

          tree bin
          file bin/*

      - name: Create files
        run: |
          echo "echo hello world" > echo_hello
          chmod +x echo_hello
          tar -c echo_hello | xz -T0 > echo_hello.tar.xz

      # - name: Upload
      #   uses: actions/upload-artifact@main
      #   with:
      #     name: ${{matrix.target_arch}}
      #     path: echo_hello.tar.xz

  build-musl-cross:
    runs-on: ubuntu-latest
    steps:

    - name: Clone build-musl-cross
      run: |
        git clone https://github.com/DanielMYT/musl-cross-make

    - name: Build
      run: |
        cd musl-cross-make

        cat<<EOF>musl-cross/config.mak
        TARGET = aarch64-linux-musl

        BINUTILS_VER = 2.41
        GCC_VER = 13.2.0
        MUSL_VER = 1.2.4
        GMP_VER = 6.3.0
        MPC_VER = 1.3.1
        MPFR_VER = 4.2.1
        ISL_VER = 0.26
        LINUX_VER = 6.6.2

        # Recommended options for smaller build for deploying binaries:
        COMMON_CONFIG += CFLAGS="-g0 -Os" CXXFLAGS="-g0 -Os" LDFLAGS="-s"
        EOF

        make -j$(nproc --all)

        ls

        tree -L 2
