name: Build musl toolchain

on:
  push:
    paths:
      - ".github/workflows/build_musl_cross.yaml"
  workflow_dispatch:

jobs:
  Build:
    permissions:
      contents: write
    name: Build ${{matrix.target}}-${{matrix.host}}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        host:
          # - x86_64-linux-musl
          - aarch64-linux-musl
        target:
          # - x86_64-linux-musl
          - aarch64-linux-musl

    steps:
      - name: Clone musl-cross-make
        run: git clone https://github.com/DanielMYT/musl-cross-make

      - name: Patch source
        working-directory: musl-cross-make
        run: |
          ## Tar no verbose
          cat Makefile | sed 's/tar zxvf/tar zxf/' | sed 's/tar jxvf/tar jxf/' | sed 's/tar Jxvf/tar Jxf/' > Makefile_tmp
          mv Makefile_tmp Makefile

      - name: Write config.mak
        working-directory: musl-cross-make
        run: |
          cat<<EOF>config.mak
          BINUTILS_VER = 2.41
          GCC_VER = 13.2.0
          MUSL_VER = 1.2.4
          GMP_VER = 6.3.0
          MPC_VER = 1.3.1
          MPFR_VER = 4.2.1
          ISL_VER = 0.26
          LINUX_VER = 6.6.2

          DL_CMD = curl -C - -Ls -o

          STAT = -static --static
          COMMON_CONFIG += CFLAGS="-g0 -Os \${STAT}" CXXFLAGS="-g0 -Os \${STAT}" LDFLAGS="-w -s \${STAT}"
          BINUTILS_CONFIG += --disable-gprofng
          EOF
      - name: Build host toolchain ${{matrix.host}}
        working-directory: musl-cross-make
        run: |
          make install TARGET=${{matrix.host}} OUTPUT=host-toolchain -j$(nproc)

      - name: Checkout host toolchain
        working-directory: musl-cross-make
        run: |
          ls -al
          file host-toolchain/bin/*

      - name: Build target toolchain ${{matrix.target}}
        working-directory: musl-cross-make
        run: |
          sudo apt install qemu-user-static binfmt-support
          export PATH=${PWD}/host-toolchain/bin:$PATH

          ${{matrix.host}}-gcc --version
          make clean
          make HOST=${{matrix.host}} TARGET=${{matrix.target}} -j$(nproc)
          make install
          mv output ${{matrix.target}}-${{matrix.host}}

      - name: Checkout target toolchain
        working-directory: musl-cross-make
        run: |
          ls -al
          file ${{matrix.target}}-${{matrix.host}}/bin/*

      - name: Compress ${{matrix.target}}-${{matrix.host}}
        working-directory: musl-cross-make
        run: |
          tar -c ${{matrix.target}}-${{matrix.host}} | xz -T0 > ${{matrix.target}}-${{matrix.host}}.tar.xz

      - name: Upload ${{matrix.target}}-cross artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{matrix.target}}-${{matrix.host}}.tar.xz
          path: musl-cross-make/${{matrix.target}}-${{matrix.host}}.tar.xz

      - name: Upload release
        uses: ncipollo/release-action@v1.13.0
        with:
          tag: "v1.0.0"
          artifacts: |
            musl-cross-make/${{matrix.target}}-${{matrix.host}}.tar.xz
          allowUpdates: true
          replacesArtifacts: true
          body: |
            * BINUTILS_VER = 2.41
            * GCC_VER = 13.2.0
            * MUSL_VER = 1.2.4
            * GMP_VER = 6.3.0
            * MPC_VER = 1.3.1
            * MPFR_VER = 4.2.1
            * ISL_VER = 0.26
            * LINUX_VER = 6.6.2
