name: test build for musl
run-name: test musl
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          repository: ${{github.repository}}
          # ref: ${{github.event.inputs.tag}}

      - name: Build for musl
        run: |
          sudo apt install musl

          cat<<EOF>hello.c
          #include <stdio.h>
          int main(){
            printf("Hello World\n");
            return 0;
          }
          EOF

          clang --target=x86_64-linux-musl hello.c
          file a.out

          . /etc/os-release
          cat<<EOF>arm-cross-compile-sources.list
          deb [arch=armhf,arm64] http://ports.ubuntu.com/ ${VERSION_CODENAME} main restricted
          deb [arch=armhf,arm64] http://ports.ubuntu.com/ ${VERSION_CODENAME}-updates main restricted
          deb [arch=armhf,arm64] http://ports.ubuntu.com/ ${VERSION_CODENAME} universe
          deb [arch=armhf,arm64] http://ports.ubuntu.com/ ${VERSION_CODENAME}-updates universe
          deb [arch=armhf,arm64] http://ports.ubuntu.com/ ${VERSION_CODENAME} multiverse
          deb [arch=armhf,arm64] http://ports.ubuntu.com/ ${VERSION_CODENAME}-updates multiverse
          deb [arch=armhf,arm64] http://ports.ubuntu.com/ ${VERSION_CODENAME}-backports main restricted universe multiverse
          EOF
          sudo mv arm-cross-compile-sources.list /etc/apt/sources.list.d/
          sudo dpkg --add-architecture arm64
          sudo apt update
          sudo apt install musl:arm64

          clang --target=aarch64-linux-musl hello.c
          file a.out
