name: Workflow template
run-name: Workflow template (${{github.event.head_commit.message}})
on:
  push:
    paths: ".github/workflows/workflow_template.yaml"
  workflow_dispatch:
    inputs:
      msg:
        description: "message:"
        default: "Hello World!"
        required: true
      # tag:
      #   description: "Release tag:"
      #   default: "v1.0"
      #   required: true

jobs:
  display-variables:
    name: ${{ vars.JOB_NAME }}
    # You can use configuration variables with the `vars` context for dynamic jobs
    if: ${{ vars.USE_VARIABLES == 'true' }}
    runs-on: ${{ vars.RUNNER }}
    environment: ${{ vars.ENVIRONMENT_STAGE }}
    steps:
    - name: Use variables
      run: |
        echo "repository variable : $REPOSITORY_VAR"
        echo "organization variable : $ORGANIZATION_VAR"
        echo "overridden variable : $OVERRIDE_VAR"
        echo "variable from shell environment : $env_var"
      env:
        REPOSITORY_VAR: ${{ vars.REPOSITORY_VAR }}
        ORGANIZATION_VAR: ${{ vars.ORGANIZATION_VAR }}
        OVERRIDE_VAR: ${{ vars.OVERRIDE_VAR }}
        
    - name: ${{ vars.HELLO_WORLD_STEP }}
      if: ${{ vars.HELLO_WORLD_ENABLED == 'true' }}
      uses: actions/hello-world-javascript-action@main
      with:
        who-to-greet: ${{ vars.GREET_NAME }}
  build:
    permissions:
      actions: write
      contents: write
    name: "Matrix msg: ${{matrix.msg}}"
    runs-on: ubuntu-latest
    env:
      arch: ${{github.event.inputs.msg}}
    strategy:
      fail-fast: false
      matrix:
        msg:
          - "Hello matrix!"

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          repository: ${{github.repository}}
          # ref: ${{github.event.inputs.tag}}

      - name: Print system info
        run: |
          cat /etc/os-release
          cat /proc/cpuinfo
          echo "Available cpu count: $(nproc)"

      - name: Print env
        run: env

      - name: Test
        run: |
          echo ${{format('Workflow template {0} {1} {2}', 'Mona', 'the', 'Octocat')}}
          echo GITHUB_RUN_ID=${GITHUB_RUN_ID}
          echo GITHUB_SERVER_URL=${GITHUB_SERVER_URL}
          command -v upx && upx --version
          command -v clang && clang --version

          tree -L 2 ${GITHUB_WORKSPACE}

            cat <<EOF
          heredoc <<EOF ${PWD}
          EOF

            cat <<EOF
            heredoc tab <<EOF ${PWD}
          EOF

            cat <<-EOF
          heredoc <<-EOF ${PWD}
          EOF

          cat <<-EOF
            heredoc tab <<-EOF ${PWD}
          EOF

          cat <<EOF
          heredoc quoted <<'EOF' ${PWD}
          EOF

          cat <<EOF
          heredoc quoted <<"EOF" ${PWD}
          EOF

      - name: Set variable
        run: |
          echo DATE=$(date +"%Y-%m-%d %H:%M:%S") >> ${GITHUB_ENV}
          ## env havent take effect yet
          echo WORKFLOW_FILENAME=$(echo ${GITHUB_WORKFLOW_REF} | grep -o -E -e "\w+\.yam?l") >> ${GITHUB_ENV}

      - name: Print the variables we set
        run: |
          echo DATE=${{env.DATE}}
          echo WORKFLOW_FILENAME=${{env.WORKFLOW_FILENAME}}

      - name: Upload
        uses: actions/upload-artifact@main
        with:
          name: os-release
          path: /etc/os-release

      - name: Upload release
        uses: ncipollo/release-action@v1.13.0
        with:
          tag: "v1.0.0"
          artifacts: |
            /etc/os-release
            /etc/resolv.conf
          allowUpdates: true
          replacesArtifacts: true
          body: |
            ${{env.DATE}}
            ${{env.WORKFLOW_FILENAME}}
            ${{github.event.head_commit.message}}
            https://github.com/zongou/actions/actions/runs/7267285191
            /${{github.repository}}/actions/${{GITHUB_RUN_ID}}

      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2.0.6
        with:
          delete_workflow_pattern: "workflow_template.yaml"
          retain_days: 0
          keep_minimum_runs: 1
