name: test build for musl
on:
  push: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          repository: ${{github.repository}}
          # ref: ${{github.event.inputs.tag}}

      - name: Print env
        run: |
          sudo apt install musl-tools
          musl-gcc --version
          musl-gcc -xc - <<EOF
          #include <stdio.h>
          int main(){
            printf("Hello World\n");
            return 0;
          }
          EOF