name: Workflow template
run-name: ${{format('Workflow template {0} {1} {2}', 'Mona', 'the', 'Octocat')}}
on:
  push:
    paths: ".github/workflows/workflow_template.yaml"
  workflow_dispatch:
    inputs:
      msg:
        description: "message:"
        default: "Hello World!"
        required: true
      # tag:
      #   description: "Release tag:"
      #   default: "v1.0"
      #   required: true

jobs:
  build:
    permissions:
      actions: write
      contents: write
    name: "Matrix msg: ${{matrix.msg}}"
    runs-on: ubuntu-latest
    env:
      arch: ${{github.event.inputs.msg}}
    strategy:
      fail-fast: false
      matrix:
        msg:
          - "Hello matrix!"

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          repository: ${{github.repository}}
          # ref: ${{github.event.inputs.tag}}

      - name: Print system info
        run: |
          cat /etc/os-release
          cat /proc/cpuinfo
          echo "Available cpu count: $(nproc)"

      - name: Print env
        run: env

      - name: Test
        run: |
          echo GITHUB_WORKFLOW=${GITHUB_WORKFLOW}
          command -v upx && upx --version
          command -v clang && clang --version

          tree -L 2 ${GITHUB_WORKSPACE}

          heredoc(){
            cat <<EOF
          heredoc_content
          EOF

            cat <<EOF
            heredoc_content
          EOF

            cat <<-EOF
          heredoc_content
          EOF

          cat <<-EOF
            heredoc_content
          EOF
          }

          heredoc

      - name: Upload
        uses: actions/upload-artifact@main
        with:
          name: os-release
          path: /etc/os-release

      - name: Set variable
        run: |
          echo DATE=$(date +"%Y-%m-%d %H:%M:%S") >> ${GITHUB_ENV}
          ## env havent take effect yet
          echo DATE=${{env.DATE}}

          echo WORKFLOW_FILENAME=$(echo ${GITHUB_WORKFLOW_REF} | grep -o -E -e "\w+\.yam?l") >> ${GITHUB_ENV}

      - name: Upload release
        uses: ncipollo/release-action@v1.13.0
        with:
          tag: "v1.0.0"
          artifacts: |
            /etc/os-release
            /etc/resolv.conf
          allowUpdates: true
          replacesArtifacts: true
          body: |
            ${{ env.DATE }}
            ${{env.WORKFLOW_FILENAME}}
            ${{ github.event.head_commit.message }}

      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2.0.6
        with:
          delete_workflow_pattern: "workflow_template.yaml"
          retain_days: 0
          keep_minimum_runs: 1
