name: Workflow template
run-name: Workflow template (${{github.event.head_commit.message}})
on:
  push:
    paths: ".github/workflows/workflow_template.yaml"
  workflow_dispatch:
    inputs:
      msg:
        description: "message:"
        default: "Hello World!"
        required: true
      # tag:
      #   description: "Release tag:"
      #   default: "v1.0"
      #   required: true

jobs:
  build:
    permissions:
      actions: write
      contents: write
    name: "Matrix msg: ${{matrix.msg}}"
    runs-on: ubuntu-latest
    env:
      arch: ${{github.event.inputs.msg}}
    strategy:
      fail-fast: false
      matrix:
        msg:
          - "Hello matrix!"

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          repository: ${{github.repository}}
          # ref: ${{github.event.inputs.tag}}

      - name: Update cache
        uses: actions/cache@v3
        with:
          path: |
            run_url
          key: workflow_template-${{ runner.os }}-${{ github.run_id }}
          restore-keys: |
            workflow_template

      - name: Test retored cache and update
        run: |
          test -f run_url && echo "preview run url: $(cat run_url)"

      - name: Set variable
        run: |
          ## env havent take effect yet
          echo DATE=$(date +"%Y-%m-%d %H:%M:%S") >> ${GITHUB_ENV}
          echo WORKFLOW_FILENAME=$(echo ${GITHUB_WORKFLOW_REF} | grep -o -E -e "\w+\.yam?l") >> ${GITHUB_ENV}
          echo GITHUB_RUN_URL=${GITHUB_SERVER_URL}/${{github.repository}}/actions/runs/${GITHUB_RUN_ID} >> ${GITHUB_ENV}

      # - name: Restore cache
      #   id: cache-restore
      #   uses: actions/cache/restore@v3
      #   with:
      #     path: |
      #       run_url
      #     key: workflow_template


      # - name: Save cache
      #   id: cache-save
      #   uses: actions/cache@v3
      #   with:
      #     path: |
      #       run_url
      #     key: primes-${{ runner.os }}-${{ github.run_id }} # Can use time based key as well
      #     restore-keys: |
      #       ${{steps.cache-restore.outputs.cache-primary-key}}
          
      - name: Print system info
        run: |
          cat /etc/os-release
          cat /proc/cpuinfo
          echo "Available cpu count: $(nproc)"

      - name: Print env
        run: env

      - name: Test
        run: |
          echo ${{format('Workflow template {0} {1} {2}', 'Mona', 'the', 'Octocat')}}
          echo ${{github.server_url}}/${{github.repository}}/actions/runs/${{github.run_id}}
          echo GITHUB_RUN_ID=${GITHUB_RUN_ID}
          echo GITHUB_SERVER_URL=${GITHUB_SERVER_URL}
          command -v upx && upx --version
          command -v clang && clang --version

          tree -L 2 ${GITHUB_WORKSPACE}

            cat <<EOF
          heredoc <<EOF ${PWD}
          EOF

            cat <<EOF
            heredoc tab <<EOF ${PWD}
          EOF

            cat <<-EOF
          heredoc <<-EOF ${PWD}
          EOF

          cat <<-EOF
            heredoc tab <<-EOF ${PWD}
          EOF

          cat <<EOF
          heredoc quoted <<'EOF' ${PWD}
          EOF

          cat <<EOF
          heredoc quoted <<"EOF" ${PWD}
          EOF

      - name: Print the variables we set
        run: |
          echo DATE=${{env.DATE}}
          echo WORKFLOW_FILENAME=${{env.WORKFLOW_FILENAME}}
          echo GITHUB_RUN_URL=${{env.GITHUB_RUN_URL}}

      - name: Upload
        uses: actions/upload-artifact@main
        with:
          name: os-release
          path: /etc/os-release

      - name: Upload release
        uses: ncipollo/release-action@v1.13.0
        with:
          tag: "v1.0.0"
          artifacts: |
            /etc/os-release
            /etc/resolv.conf
          allowUpdates: true
          replacesArtifacts: true
          body: |
            [action](${{github.server_url}}/${{github.repository}}/actions/runs/${{github.run_id}})
            ${{env.DATE}}
            ${{env.WORKFLOW_FILENAME}}
            ${{github.event.head_commit.message}}

      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2.0.6
        with:
          delete_workflow_pattern: "workflow_template.yaml"
          retain_days: 0
          keep_minimum_runs: 1
